### ISSUE TITLE
add singleplayer

### ISSUE THREAD

**Issue by judethe-coder** [LAX1DUDE/eaglercraft#124] opened 2022-02-23 15:28 UTC
pls add single player

**Comment by French-Cat** [comment] 2022-02-23 16:41
As this is a common question thats most likely in a FAQ somewhere I highly doubt you are going to get an answer from the developer. Therefore I will answer this for you, this is currently not possible due to having to store the world and its data somewhere which is not exactly possible since your playing on a browser. You can easily host your own server and if you configure it right, you can make it private and play by yourself. If you have any stupid questions I will remain in this issue so ask away.

**Comment by French-Cat** [comment] 2022-02-23 16:43
Here are the steps to create a server ( I am assuming you are on a chromebook. )
go to https://replit.com/@ayunami2000/eaglercraft-server
click fork
click run
And your done.
Again if you configure the server properties right you can have a 100% private server.

**Comment by bigburger687** [comment] 2022-02-23 19:41
https://replit.com/@ayunami2000/eaglercraft-server

it is blocked for me can you try using code sandbox plz

**Comment by judethe-coder** [comment] 2022-02-23 19:44
is there any way you can make something where you can play it without internet

**Comment by judethe-coder** [comment] 2022-02-23 19:51
also replit is blocked for me too

**Comment by French-Cat** [comment] 2022-02-23 19:55
Code sandbox would not be an option for hosting, you could try a proxy that would allow you to bypass restrictions.

**Comment by bigburger687** [comment] 2022-02-23 20:01
which one mikes proxy is blocked

**Comment by bigburger687** [comment] 2022-02-23 20:03
![image](https://user-images.githubusercontent.com/72570433/155398794-e2cc5bd6-bfd4-4fc9-b284-d6b51d2391f9.png)

**Comment by bigburger687** [comment] 2022-02-23 20:06
or any other codeing sight

**Comment by ethanaobrien** [comment] 2022-02-23 20:08
This is a duplicate of #7

**Comment by bigburger687** [comment] 2022-02-23 20:10
it is not

**Comment by French-Cat** [comment] 2022-02-23 20:54
It is though

**Comment by LAX1DUDE** [comment] 2022-02-23 21:03
> it is not

You need to shut the fuck up right now, this is your 8th comment on this duplicate issue whining like a little bitch over something we have all spent hours trying to answer to countless other retards who also have no idea how to use this site.

Here are all the fucking duplicate issues, all of which you could've read but you still chose to make a new one:

Issue [#108](https://github.com/LAX1DUDE/eaglercraft/issues/108)
Issue [#106](https://github.com/LAX1DUDE/eaglercraft/issues/106)
Issue [#79](https://github.com/LAX1DUDE/eaglercraft/issues/79)
Issue [#46](https://github.com/LAX1DUDE/eaglercraft/issues/46)
Issue [#45](https://github.com/LAX1DUDE/eaglercraft/issues/45)
Issue [#30](https://github.com/LAX1DUDE/eaglercraft/issues/30)
Issue [#119](https://github.com/LAX1DUDE/eaglercraft/issues/119)
Issue [#7](https://github.com/LAX1DUDE/eaglercraft/issues/7)

Get the fuck off of this site

**Closed by LAX1DUDE** 2022-02-23 21:03 UTC
